---
server:
  port: 8080
  servlet:
    context-path: /api

management:
  info:
    git:
      mode: full
  server:
    servlet:
      context-path: /monitor
      port: 8088 #manager port
  endpoint:
    shutdown:
      enabled: true

endpoints:
  features:
    sensitive: true

info:
  app:
    name: gagatech-mana
    version: 1.0

spring:
  security:
    user:
      name: admin
      password: admin
    basic:
      path:
        - /monitor/**
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true


  flyway:
    aseline-on-migrate: true
    locations: classpath:db/migration
